version: '3'
services:
  database:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=itau_dashboard
      - POSTGRES_PASSWORD=1234
    volumes:
      - pg-data:/var/lib/postgresql
  api: 
    build: ./api/v1
    ports:
      - 5000:5000
    depends_on:
      - database
  dashboad:
    build: ./dashboard
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  pg-data: